name: bambam_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.0.1
  provider: ^6.1.2
  go_router: ^17.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
